version: '3.1'

services:
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    command: >
      bash -c "cp /opt/spark/external-jars/postgresql-42.7.3.jar /opt/spark/jars/ &&
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master --port 7077 --webui-port 8081"
    ports:
      - "7077:7077"
      - "8081:8081"
    volumes:
      - ./include:/usr/local/airflow/include
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./jars:/opt/spark/external-jars
    networks:
      - airflow

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    command: >
      bash -c "cp /opt/spark/external-jars/postgresql-42.7.3.jar /opt/spark/jars/ &&
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077 --cores 2 --memory 2G --webui-port 8082"
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    volumes:
      - ./include:/usr/local/airflow/include
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./jars:/opt/spark/external-jars
    networks:
      - airflow

  my_postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: abdo
      POSTGRES_PASSWORD: abdo
      POSTGRES_DB: airflow_dw
    ports:
      - "5433:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    networks:
      - airflow

volumes:
  my_postgres_data:

networks:
  airflow:
    external: true
    name: airflow-pyspark_22e9af_airflow
